services:
    kfi_cms.twig.extension:
        arguments: [@router]
        class: KFI\CMSBundle\Twig\Extensions\CMSExtension
        tags:
            - { name: twig.extension }
    kfi.ecommerce.admin.brand:
        class: KFI\CMSBundle\Admin\PostAdmin
        tags:
            -
              name: sonata.admin
              manager_type: orm
              group: CMS
              label: Post
              label_catalogue: admin
              label_translator_strategy: sonata.admin.label.strategy.underscore
        arguments: [null, KFI\CMSBundle\Entity\Post, KFICMSBundle:PostAdmin]
        calls: [ [ setTranslationDomain, [ KFICMSBundle ] ] ]