services:
    kfi_cms.twig.extension:
        arguments: [@router]
        class: KFI\CMSBundle\Twig\Extensions\CMSExtension
        tags:
            - { name: twig.extension }
    kfi_cms.admin.post:
        class: KFI\CMSBundle\Admin\PostAdmin
        tags:
            -
              name: sonata.admin
              manager_type: orm
              group: CMS
              label: Post
              label_catalogue: admin
              label_translator_strategy: sonata.admin.label.strategy.underscore
        arguments: [null, KFI\CMSBundle\Entity\Post, KFICMSBundle:Model\WebPageAdmin]
        calls: [ [ setTranslationDomain, [ KFICMSBundle ] ] ]
    kfi_cms.admin.category:
        class: KFI\CMSBundle\Admin\CategoryAdmin
        tags:
            -
              name: sonata.admin
              manager_type: orm
              group: CMS
              label: Category
              label_catalogue: admin
              label_translator_strategy: sonata.admin.label.strategy.underscore
        arguments: [null, KFI\CMSBundle\Entity\Category, KFICMSBundle:Model\WebPageAdmin]
        calls: [ [ setTranslationDomain, [ KFICMSBundle ] ] ]
    kfi_cms.admin.tag:
        class: KFI\CMSBundle\Admin\TagAdmin
        tags:
            -
              name: sonata.admin
              manager_type: orm
              group: CMS
              label: Tag
              label_catalogue: admin
              label_translator_strategy: sonata.admin.label.strategy.underscore
        arguments: [null, KFI\CMSBundle\Entity\Tag, KFICMSBundle:Model\WebPageAdmin ]
        calls: [ [ setTranslationDomain, [ KFICMSBundle ] ] ]

    kfi_cms.form.type.post.categories:
        class: KFI\CMSBundle\Form\Type\PostCategoriesType
        arguments: [ @doctrine.orm.entity_manager, KFI\CMSBundle\Entity\Category ]
        tags: [ { name: form.type, alias: kficms_post_categories } ]